services:
  db:
    image: postgres
    container_name: dineqr
    environment:
      POSTGRES_DB: dineqr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordishard
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata:
