# Generated by Django 6.0.4 on 2026-05-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_review_order_alter_review_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('reason', models.CharField(choices=[('water', 'Need Water'), ('bill', 'Bring Bill'), ('clean', 'Clean Table'), ('help', 'Need Assistance')], default='help', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='mild', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
