# Generated by Django 6.0.4 on 2026-05-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_paid_order_paid_at_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='mild', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
