# Generated by Django 6.0.4 on 2026-06-03 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_waitercall_menuitem_best_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='best_seller',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured/Recommended'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('sweet', 'Sweet'), ('neutral', 'Neutral'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='waitercall',
            name='reason',
            field=models.CharField(choices=[('water', 'Need Water'), ('bill', 'Bring Bill'), ('clean', 'Clean Table'), ('help', 'Need Assistance'), ('paid', 'Payment Done')], default='help', max_length=20),
        ),
    ]
