# Generated by Django 6.0.4 on 2026-07-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_kitchenbroadcast_tablesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='waitercall',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
