# Generated by Django 6.0.4 on 2026-05-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_tablesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='best_seller',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured/Recommended'),
        ),
    ]
