# Generated by Django 6.0.4 on 2026-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menuitem_best_seller_menuitem_preparation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('reason', models.CharField(choices=[('water', 'Need Water'), ('bill', 'Bring Bill'), ('clean', 'Clean Table'), ('help', 'Need Assistance')], default='help', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
