# Generated by Django 6.0.4 on 2026-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_menuitem_best_seller_menuitem_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitercall',
            name='reason',
            field=models.CharField(choices=[('water', 'Need Water'), ('bill', 'Bring Bill'), ('clean', 'Clean Table'), ('help', 'Need Assistance'), ('paid', 'Payment Done')], default='help', max_length=20),
        ),
    ]
