# Generated by Django 6.0.4 on 2026-07-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_waitercall_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
