# Generated by Django 6.0.4 on 2026-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_waitercall_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
