# Generated by Django 6.0.4 on 2026-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_menuitem_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.CharField(choices=[('GRILL', 'Grill & Hot Kitchen'), ('BAR', 'Bar & Drinks'), ('FRYER', 'Fryer & Snacks'), ('PANTRY', 'Salads & Desserts')], default='GRILL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready')], default='received', max_length=20),
        ),
    ]
