# Generated by Django 6.0.4 on 2026-05-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_tablesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableSession',
        ),
    ]
