# Generated by Django 6.0.4 on 2026-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_menuitem_station_order_updated_at_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.CharField(choices=[('Mains', 'Khana & Main Kitchen'), ('Snacks', 'Snacks & Fryer'), ('Bar', 'Bar & Drinks'), ('DESSERT', 'Salads & Desserts')], default='Mains', max_length=20),
        ),
    ]
