# Generated by Django 6.0.4 on 2026-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_paid_amount_orderitem_paid_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('sweet', 'Sweet'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='neutral', max_length=10),
        ),
    ]
