# Generated by Django 6.0.4 on 2026-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_menuitem_spice_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='mild', max_length=10),
        ),
    ]
