# Generated by Django 6.0.4 on 2026-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_menuitem_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitercall',
            name='reason',
            field=models.CharField(choices=[('water', 'Need Water'), ('bill', 'Bring Bill'), ('clean', 'Clean Table'), ('help', 'Need Assistance'), ('paid', 'Payment Done'), ('food_ready', 'Food Ready for Pickup')], default='help', max_length=20),
        ),
    ]
