# Generated by Django 6.0.4 on 2026-06-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_menuitem_spice_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('sweet', 'Sweet'), ('neutral', 'Neutral'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='neutral', max_length=10),
        ),
    ]
