# Generated by Django 6.0.4 on 2026-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('cart_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
